name: Deploy FastAPI Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn requests python-dotenv
      - name: Start the application
        run: |
          uvicorn main:app --reload
        env:
          POKEMON_TCG_API_KEY: ${{ secrets.POKEMON_TCG_API_KEY }}
